# Generated by Django 4.2.7 on 2023-12-06 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('receiver_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_message', to='user.profile')),
                ('sender_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to='user.profile')),
            ],
            options={
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
