# Generated by Django 4.2.7 on 2023-12-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_followed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='personal_id',
        ),
    ]
